export enum Provincias {
  ASCOPE = 'ASCOPE',
  BOLIVAR = 'BOLIVAR',
  CHEPEN = 'CHEPEN',
  GRAN_CHIMU = 'GRAN CHIMU',
  JULCAN = 'JULCAN',
  OTUZCO = 'OTUZCO',
  PACASMAYO = 'PACASMAYO',
  PATAZ = 'PATAZ',
  SANCHEZ_CARRION = 'SANCHEZ CARRION',
  SANTIANGO_DE_CHUCO = 'SANTIANGO DE CHUCO',
  TRUJILLO = 'TRUJILLO',
  VIRU = 'VIRU',
}
